apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
spec:
  selector:
    matchLabels:
      app: nginx-app-marcel
  replicas: 3
  template:
    metadata:
      labels:
        app: nginx-app-marcel
    spec:
      containers:
      - name: nginx
        image: nginx:1.14.2
        ports:
        - containerPort: 80
      serviceAccount: nginx-sa
      serviceAccountName: nginx-sa
